apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  namespace: openshift-logging
spec:
  managementState: Managed
  size: 1x.demo
  storageClassName: gp3-csi
  storage:
    schemas:
      - version: v13
        effectiveDate: "2024-06-01"
    secret:
      name: logging-loki-s3
      type: s3
  tenants:
    mode: openshift-logging
  limits:
    global:
      retention:
        days: 3
